// import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

import { Open_Sans } from "@next/font/google";
import Link from "next/link";

// These styles apply to every route in the application
import "./globals.css";
import styles from "./rootStyle.module.css";

const inter = Open_Sans({
  subsets: ["latin"],
  weight: ["400"],
});


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
    <head />
    <body>
      <header>
        <h1>
          <Link className={styles.homeLink} href={"/home"}>
            GLOBOMANTICS
          </Link>
        </h1>
        <h3>
          <Link className={styles.menuBarLinks} href="/blog">
            Blog
          </Link>
        </h3>
        <h3>
          <Link className={styles.menuBarLinks} href="/settings">
            Settings
          </Link>
        </h3>
        <h3>
          <Link className={styles.menuBarLinks} href="/conference">
            Conference
          </Link>
        </h3>
      </header>
      {children}
    </body>
  </html>
  )
}
